### ISSUE TITLE
Replace/Remove ueberzug

### ISSUE THREAD

**Issue by SunPodder** [tramhao/termusic#141]
ueberzug is no longer maintained. That would not be a big problem. But the last commit of the author removed all code though he still kept the repository. I tried installing it with pip, but he removed that from pip also. I also could not find it on the apt package repositories (ubuntu/mint).

So i think it's best to remove ueberzug as a dependency.

**Comment by GokhanPolat** [comment]
Hi @SunPodder,
I'm not tried yet but there is a repo and they had been saying dropin replacement of ueberzug. May be you would like to give a chance.
https://github.com/jstkdng/ueberzugpp

**Comment by hasezoey** [comment]
there is also a continuation project, which basically replaced all the officially shipped packages: [`ueber-devel/ueberzug`](https://github.com/ueber-devel/ueberzug) (at least on arch).

also ueberzug is not a hard dependency, it could always be disabled by not having the `cover` feature enabled, now since 14425ddfb46730496954ccb21767df1af2187ffa you can just not enable `cover-ueberzug` and not have anything related to ueberzug compiled in (though you can still use `cover-viuer` for sixel, kitty and iterm protocols).
