### ISSUE TITLE
GStreamer discussion

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#232]
I open this issue because @tramhao noted that there are some issues with the gstreamer backend, but it is currently to me unknown what those issues are and to provide a place to discuss those instead of de-railing other issues, references:
- https://github.com/tramhao/termusic/issues/230#issuecomment-1989718562
- https://github.com/tramhao/termusic/pull/221#issuecomment-1975675996

@tramhao could you please explain what those issues are supposed to be in the `master` branch and what your current problem is in the `dev` branch (or why to change to `gstreamer-play`)?

**Comment by tramhao** [comment]
Both in master branch and dev branch, the end-of-stream signal is not received from message bus. In Master branch, I saw that you're using another Arc<Mutex<>> to store this as a fallback. This works for this 1st time. I mean for the first track, after about-to-finish signal, it'll generate EOS. For the 2nd track and tracks after, it's not working. So the track will not move to next after 2nd track finish.
In dev branch, I'm using another crate gstreamer-play and not playbin directly. Because gstreamer-play is supposed to be a replacement of gstreamer-player, it's working great for other things like seek. Seek is more smoothly than master branch. However, as end-of-stream signal is still missing, it'll not move to 2nd track unless skip by hand.
I believe it's because something changed in upstream. When I started working with playbin3, the end-of-stream signal is very easy to get.

**Comment by hasezoey** [comment]
> Both in master branch and dev branch, the end-of-stream signal is not received from message bus. In Master branch, I saw that you're using another Arc<Mutex<>> to store this as a fallback. This works for this 1st time. I mean for the first track, after about-to-finish signal, it'll generate EOS. For the 2nd track and tracks after, it's not working. So the track will not move to next after 2nd track finish.

if what i read in gstreamer's documentation is correct, gstreamer's EOF is only send *if there is nothing queued up* and the track ends, hence i needed to do a workaround to triggered our EOF signal in either gstreamer's EOF or in the next track start signal.

i also just tested in 3560924113989c6a17616ea2143c7f3d79fb87c9, and yes i can confirm that it actually only works for one track, i will try to fix it again later

**Comment by tramhao** [comment]
but I remember in gstreamer-rs v0.20 and before, eos is sending after each track ends. Do you know if there are related changes? I searched the release notes and changelog,but didn'tfind anything.

**Comment by tramhao** [comment]
Actually about to finish and eos need to work together. But I can only find a small app using about to finish for gapless called soi. It still use old version gstream-rs and haven't update during last two years.

**Comment by hasezoey** [comment]
> but I remember in gstreamer-rs v0.20 and before, eos is sending after each track ends. Do you know if there are related changes? I searched the release notes and changelog,but didn'tfind anything.

was this when coincidentally no "gapless" playback was implemented?

i have made some further testing, and what i said about "gstreamer documentation" may be wrong, i have not found a source in the documentation, so here are my findings:
When our "gapless" is disabled, we dont set the `uri` parameter until the EOS event has been given to us from gstreamer.
When our "gapless" is enabled, we set the `uri` parameter in the `about-to-finish` signal, which makes gstreamer treat it as a continuous stream and so is not sending a EOS on track end (but still sending a `StreamStart`)

---

as for the track change issue, it was a simple race-condition i didnt consider, pushing a PR in a sec

**Comment by tramhao** [comment]
Perhaps this is the way to go: When gapless enabled, detect stremstart. When gapless disabled, detect eos.
When skipping, the EOS is send by skip command, so no need to detect.

**Comment by hasezoey** [comment]
> Perhaps this is the way to go: When gapless enabled, detect stremstart. When gapless disabled, detect eos.
>  When skipping, the EOS is send by skip command, so no need to detect.

this is basically how it works with the workaround i put in, though there is no special handling for "gapless disabled" at the moment as it "just works" (both with gapless enabled or disabled; at least in my testing)

---

are there any other problems that need to be dealt with? also changing to `gstreamer-play`, is this still something we should do?

**Comment by tramhao** [comment]
There is still one thing I think gstreamer-play done better, the seeking. Currently in master branch, the seeking is adjusted with mute and pause, because when I implement it, without mute and pause, there will be runtime error when seeking continuously. In dev branch, the seeking just works with better result, with feedback on progress bar.

**Comment by hasezoey** [comment]
> Currently in master branch, the seeking is adjusted with mute and pause, because when I implement it, without mute and pause, there will be runtime error when seeking continuously

(on `master`, 931d379d0477da0dcd9ab96aeda0ae88c9824812)
i just looked at the gstreamer seeking code, and i dont see any pausing / unpausing.
i have also tried running it without the volume setting, and it just works without artifacts.

**Comment by tramhao** [comment]
I think now playbin3 works without problem and this issue can be closed. Before new version, some small bugs in issue list need to be fixed. Thanks.
