### ISSUE TITLE
Bug the playback speed of gstreamer backend is not applied when initializing

### ISSUE THREAD

**Issue by tramhao** [tramhao/termusic#279]
## Environment & Versions

Latest master b6f877

- System:  
-Linux arch 6.8.2
- Termusic version: 
-Termusic v0.9.0-129-gb6f87753-dirty[g]

- Rust version: 1.77.1

Logs:

log file is empty. No errors logged for this.

## Description of the Problem
When a speed other than default value(10) is saved, close the app, and reopen, the speed is not applied to gstreamer backend. rusty and mpv is no problem.

**Comment by hasezoey** [comment]
can reproduce (on 236fb4d015f49ce0408ac58a8a7839b7941eeff5), from my quick investigation, the `speed` is set and send, but GST does not handle it (`sink.send_event` returns `false`).
also from further investigation, this seems to be because the state at the time is `::Null`, and so it can only be set in other states (`::Ready`, `::Playing` and `::Paused`).
