### ISSUE TITLE
Add support for sixel

### ISSUE THREAD

**Issue by CRAG666** [tramhao/termusic#322]
https://en.wikipedia.org/wiki/Sixel
I use foot terminal

**Comment by hasezoey** [comment]
sixel is already supported in master, you need to enable [`cover-viuer-sixel` feature](https://github.com/tramhao/termusic/blob/000807018324aa87bf7420d96c981938943da9ca/tui/Cargo.toml#L71) though

**Comment by CRAG666** [comment]
@hasezoey thanks, how to set position the image in sixel?

**Comment by hasezoey** [comment]
it should work the same regardless of what backend is used, you can:
- configure it via the config file(in v1 its `[album_photo_xywh]`)
- configure size / position via `CTRL+SHIFT+ARROW KEYS / PGUP / PGDOWN` or hide via `CTRL+SHIFT+END`, the only thing that cannot be configured this way is the alignment

**Comment by uwidev** [comment]
I'm not too sure if this is a sixel issue or a foot issue, but I have this issue where album art is unresponsive or is rendered poorly. I can't even hide it.

I'm also using the foot terminal and building it from master (AUR `termusic-git`). Since I'm using foot, as expected I'm on a wayland environment (hyprland).

Something I didn't quite understand is that you said that it needs to be "enabled". How is this done? I couldn't find anything in the configuration files in `~/.config/termusic/`. `Does it just look for fallbacks until it finds sixel? I removed the ueberzugpp package as a dependency to try to force it to use sixel, but it didn't change anything.

This picture is how the album art looks like after trying to move it down several times.
![2024-06-20-163426_hyprshot](https://github.com/tramhao/termusic/assets/10101319/d5647613-cdce-4346-8d3b-2ba1f36e9c57)

**Comment by hasezoey** [comment]
> Does it just look for fallbacks until it finds sixel? I removed the ueberzugpp package as a dependency to try to force it to use sixel, but it didn't change anything.

AUR `termusic-git` compiles with `--all-features` meaning all cover targets are enabled by default, though the priority list is: `kitty > iterm > sixel > uberzug`
[source](https://github.com/tramhao/termusic/blob/409bdba9ed5f51ef71a186a479f5759e376e975f/tui/src/ui/model/mod.rs#L131-L146)

> Something I didn't quite understand is that you said that it needs to be "enabled". How is this done? I couldn't find anything in the configuration files in ~/.config/termusic/

Since my comment above config version v2 has been merged which has different header names and file names, for v2 look infile  `tui.toml` under header `coverart`.
As for enablement, it is enabled by default if compiled with any "cover" feature and your terminal supports it, it can only be disabled via the cli flag `-c` or `--disable-cover` currently.

Please note that the art display is quite a mess currently and is known to not clear correctly is some cases. (like #250, #115)

PS: config v2 is layout out so that cover art is not really meant to be re-positioned aside from alignment, but other parts still need adjustment to this

---

if you want to continue or more properly report your issue, please open a new issue as this issue is about *adding* sixel support not *problems with it*
