### ISSUE TITLE
How to change to ipv4 (bug?)

### ISSUE THREAD

**Issue by Shringe** [tramhao/termusic#368]
## Environment & Versions

- System: Arch Linux
- Termusic version: termusic-git (Termusic v0.9.1-17-g843ac945[g])

- Rust version: cargo 1.81.0 (2dbb1af80 2024-08-20)

## Description of the Problem
Whenever I set `address = "0.0.0.0"` in `~/.config/termusic/server.toml` termusic opens with ipv4 once, and then overwrites the config back to `address = "::"` when it quits. I don't see an option inside the graphical config to change this either. Is this how you're supposed to set ipv4? NordVPN blocks ipv6 and the termusic tui won't open without being set to ipv4 first.

**Comment by tramhao** [comment]
I checked on arch and set the address to "0.0.0.0" or "127.0.0.1" both works without being revert back to default. Would you please try the master version? Thanks.

**Comment by hasezoey** [comment]
> Would you please try the master version? Thanks.

the version reported *is the current master* 843ac945

**Comment by hasezoey** [comment]
> Is this how you're supposed to set ipv4?

yes this is (to my knowledge) how to set to use ipv4.

> NordVPN blocks ipv6

i am curious, shouldnt it only block outgoing / incoming ipv6?

> Whenever I set address = "0.0.0.0" in ~/.config/termusic/server.toml termusic opens with ipv4 once, and then overwrites the config back to address = "::" when it quits

i cannot reproduce this by just opening up termusic and quitting or opening the config editor saving then quitting.

do you maybe have a termusic-server process still around when you tried editing the file? because termusic-server currently re-saves on exit. (ie if the old process was started with the old values, then you write the config, then quit the process, the settings from the old process overwrite the ones set by you in the meantime)

**Comment by Shringe** [comment]
I'm also no longer able to reproduce this issue. I thought I had checked for termusic processes before setting the config, but it's possible that I didn't. I'm not sure why NordVPN blocks local connections by default, but its Linux support isn't perfect regardless.
