### ISSUE TITLE
album art via ueberzug fails

### ISSUE THREAD

**Issue by m4b** [tramhao/termusic#41]
I installed ueberzug on the device I was testing on, but it still fails to run, with a broken pipe right here: https://github.com/tramhao/termusic/blob/94c45fc8960b15efd78a2c5f58b7642f1a4f2109/src/ueberzug.rs#L65

Note: i was running termusic via an ssh session, so I did not have `DISPLAY` env variable set; I tested by running with `WAYLAND_DISPLAY=wayland-0 DISPLAY=:0` but it makes no difference. Is there a way to run without this feature?

I am also seeing the next track not playing *sometimes* in the playlist, and I'm wondering if it's caused by this?

**Comment by tramhao** [comment]
Ueberzug need to have local display I think. You can compile without feature flag "cover", or you can run with kitty terminal, because kitty support display with viuer and it'll prefer to display with viuer. 
Next track should works unless program doesn't know the duration of track, thus don't know when to stop.

**Comment by tramhao** [comment]
In v0.7.0 you can disable cover display by option `-c` when no display is available. Closing this issue for now.

**Comment by rszyma** [comment]
Installing via AUR on wayland and running termusic gives error: 

```
update photo error: Failed to run Ueberzug: Broken pipe (os error 32)
```
