### ISSUE TITLE
currently playing timestamp not updating for ogg/vorbis

### ISSUE THREAD

**Issue by michaelkirk** [tramhao/termusic#70]
The music plays, but the time stamp stays at some fixed value (e.g. "00:00 -01:39") for me. 

When I press`l` to play the next ogg in the playlist, the title name updates, but not the timestamp. The duration that's stuck there is from whatever was the previous non-ogg (i.e. mp3) file.

Interestingly, there *are* accurate durations listed alongside the .ogg files in the playlist. And yet the "currently playing" timestamps that don't update to reflect that duration, or the current position, when paying an ogg.

Notice how the next track "Blue Grains" has a duration of 6:49 in the playlist (this is the correct duration)
<img width="1010" alt="Screen Shot 2022-05-03 at 10 41 30 AM" src="https://user-images.githubusercontent.com/217057/166508902-04f43045-c904-4f1d-b31a-6b50c411f19b.png">

But once it's playing, the duration is not updated from wherever it was when I hit (l).
<img width="1011" alt="Screen Shot 2022-05-03 at 10 42 32 AM" src="https://user-images.githubusercontent.com/217057/166509075-67d0a33b-488e-4c44-85f5-920d14de27f9.png">

I don't see this behavior when `l`'ing mp3s.

Note sure if it's relevant, but I'm on a mac.

**Comment by tramhao** [comment]
I think it's because I use different package for parsing the duration and updating the timestamp. Parsing the duration is handled by lofty, which is correct. But playing timestamp and duration both come from player, which is by default symphonia. I think there are still some bugs when I decode ogg/vorbis by symphonia. Basically I rip the code of rodio but don't know the full process. It should be a bug in my code.

**Comment by tramhao** [comment]
If you use mpv or gstreamer backend, it'll be all right for ogg/vorbis?

**Comment by tramhao** [comment]
I think I fixed it in dev branch commit: bd031c587ec898118d9672fe038fe1bd3390c415. Please check if it works on your ogg files. Thanks.

**Comment by michaelkirk** [comment]
The timestamps now update, thanks!
