### ISSUE TITLE
update photo error

### ISSUE THREAD

**Issue by shareghzade** [tramhao/termusic#76]
when i open the termusic this error will popup:

**update photo error: Failed to run Ueberzug: No
such file or directory (os error 2)**

**Comment by tramhao** [comment]
This is because your binary package comes with cover feature, but you don't have ueberzug installed. 
To fix this: 
In arch, `paru -S ueberzug`. In other systems, please check ueberzug repo for installation: https://github.com/seebye/ueberzug

You can also use kitty terminal. Another way to fix, is to build without cover feature. Thanks.

**Comment by shareghzade** [comment]
thank you
