### ISSUE TITLE
volume sets in config.toml doesn't work

### ISSUE THREAD

**Issue by shareghzade** [tramhao/termusic#79]
Hi,
I've set volume to 10 in config.toml but when i open termusic and play the songs the volume is 70
![2022-05-30_21-02](https://user-images.githubusercontent.com/59317713/171032627-ad61e810-ce3b-4c95-8ca0-3e21c6e72550.png)
![2022-05-30_21-02_1](https://user-images.githubusercontent.com/59317713/171032666-0aa1ed68-2d61-4afe-a5c8-f7be1ef3e489.png)

**Comment by tramhao** [comment]
The default volume is 70. If it goes back to 70, it means that the config file is rewritten by program. Generally it's because there are some added config options. Maybe you're launching a new version of termusic for the first time?  
But after that, it should be working. By the way, generally you don't need to change volume in config.toml, as every time the volume will be saved to config.toml when you quit termusic. Thanks.

**Comment by tramhao** [comment]
Closing this issue for now but if you have further questions, please don't hesitate reopen it or open a new issue. Thanks so much:)
